export const categorias = [
	{
		title: "Autoinmunidad",
		imgUrl: "../img/iconosNuevos/Autoinmunidad.png",
		hexColor: "#00ABA1",
		productos: [
			{
				title: "Procesador automático para imagen",
				brand: "Biosystems",
				category: "Autoinmunidad",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/IFI i-Pro.png",
			},
		],
	},
	{
		title: "Contadores hematológicos",
		imgUrl: "../img/iconosNuevos/Contadores Hemotalógicos.png",
		hexColor: "#714284",
		productos: [
			{
				title: "Sysmex XP300",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XP300.png",
			},
			{
				title: "XN-L 350",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 350.png",
			},
			{
				title: "XN-L 450",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 450.png",
			},
			{
				title: "XN-L 450",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 450.png",
			},
			{
				title: "Sysmex XN1000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN1000.png",
			},
			{
				title: "Sysmex XN 2000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN2000.png",
			},
			{
				title: "Sysmex XN 3000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN3000.png",
			},
			{
				title: "Sysmex XN 9000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN9000.png",
			},
			{
				title: "Análisis de imágenes celulares",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Point of care",
		imgUrl: "../img/iconosNuevos/Point of care.png",
		hexColor: "#D8E6C0",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Anatomía Patológica",
		imgUrl: "../img/iconosNuevos/Anatomía Patológica.png",
		hexColor: "#E676BA",
		productos: [
			{
				title: "Benchmark GX",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Benchmark XT",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "DP200 ",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Endocrinología, Inmuno, Marcadores tumorales",
		imgUrl:
			"../img/iconosNuevos/Endocrinología, Inmuno, Marcadores tumorales.png",
		hexColor: "#FFBF30",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Química Clínica",
		imgUrl: "../img/iconosNuevos/Química Clínica.png",
		hexColor: "#6B8C49",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Banco de sangre",
		imgUrl: "../img/iconosNuevos/Banco de sangre.png",
		hexColor: "#FF5757",
		productos: [
			{
				title: "cobas e 411",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas e 503",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas e 801",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas 5800",
				brand: "cobas",
				category: "Biología Molecular / NAT",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Electroforesis",
		imgUrl: "../img/iconosNuevos/Electroforesis.png",
		hexColor: "#FFE1BD",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Software",
		imgUrl: "../img/iconosNuevos/Software.png",
		hexColor: "#D0D4D7",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Biología Molecular",
		imgUrl: "../img/iconosNuevos/Biología Molecular.png",
		hexColor: "#0697D5",
		productos: [
			{
				title: "cobas 5800",
				brand: "cobas",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas Liat",
				brand: "cobas",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "BD Max",
				brand: "BD",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Eritrosedimentación",
		imgUrl: "../img/iconosNuevos/Eritrosedimentaciòn.png",
		hexColor: "#0E0D0D",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Soluciones para suero",
		imgUrl: "../img/iconosNuevos/Soluciones para suero.png",
		hexColor: "#132E4A",

		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Cardiología",
		imgUrl: "../img/iconosNuevos/Cardiología.png",
		hexColor: "#7B1314",
		productos: [
			{
				title: "cobas h232",
				brand: "cobas",
				category: "Cardiología / Point of care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas e 411",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas Pure",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología/ Quimica",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "cobas Pro",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología/ Quimica",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Microbiología",
		imgUrl: "../img/iconosNuevos/Microbiología.png",
		hexColor: "#EE913E",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Veterinaria",
		imgUrl: "../img/iconosNuevos/Veterinaria.png",
		hexColor: "#5271FF",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Citrometría de flujo",
		imgUrl: "../img/iconosNuevos/Citometría de flujo.png",
		hexColor: "#F2BC7D",
		productos: [
			{
				title: "BD FACSAria",
				brand: "BD",
				category: "Citometría de Flujo",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "BD FACSCanto",
				brand: "BD",
				category: "Citometría de Flujo",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Medio interno",
		imgUrl: "../img/iconosNuevos/Medio Interno.png",
		hexColor: "#FFD5F2",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Coagulación",
		imgUrl: "../img/iconosNuevos/Coagulaciòn.png",
		hexColor: "#A7EAED",
		productos: [
			{
				title: "Coaguchek XS",
				brand: "Coagucheck",
				category: "Equipos Point of Care",
				type: "Coagulación / Point of Care",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "CoaguChek Pro",
				brand: "Coagucheck",
				category: "Equipos Point of Care",
				type: "Coagulación / Point of Care",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "t411",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "t511",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "STA Compact Max3",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Star Max",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "STA Satellite Max",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "DT100",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "KC4",
				brand: "Tcoag",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Destiny Plus",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Destiny Max",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Col1",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Col2",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "Col4",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
	{
		title: "Orina",
		imgUrl: "../img/iconosNuevos/Orina.png",
		hexColor: "#7F7B7E",
		productos: [
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
			{
				title: "nombre",
				brand: "Marca",
				category: "Categoria",
				type: "tipo",
				pdfUrl: "../docs/instrumentalLiviano/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/imagen.png",
			},
		],
	},
];
