export const categorias = [
	{
		title: "Autoinmunidad",
		imgUrl: "../img/iconosNuevos/Autoinmunidad.png",
		hexColor: "#00ABA1",
		productos: [
			{
				title: "Procesador automático para IFI i-Pro",
				brand: "Biosystems",
				category: "Autoinmunidad",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/IPRO.pdf",
				imgUrl: "../img/instrumentalLiviano/IFI i-Pro.png",
			},
		],
	},
	{
		title: "Contadores hematológicos",
		imgUrl: "../img/iconosNuevos/Contadores Hemotalógicos.png",
		hexColor: "#714284",
		productos: [
			{
				title: "Sysmex XP300",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/Sysmex XP 300.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XP300.png",
			},
			{
				title: "XN-L 350",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN-L 350 450 y 550.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 350.png",
			},
			{
				title: "XN-L 450",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN-L 350 450 y 550.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 450.png",
			},
			{
				title: "XN-L 550",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN-L 350 450 y 550.pdf",
				imgUrl: "../img/instrumentalLiviano/XN-L 450.png",
			},
			{
				title: "Sysmex XN1000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN-1000.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN1000.png",
			},
			{
				title: "Sysmex XN 2000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN Series 2000, 3000, 9000.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN 2000.png",
			},
			{
				title: "Sysmex XN 3000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN Series 2000, 3000, 9000.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN 3000.png",
			},
			{
				title: "Sysmex XN 9000",
				brand: "Sysmex",
				category: "Equipos Automáticos",
				type: "Contadores Hematológicos",
				pdfUrl: "../docs/instrumentos/XN Series 2000, 3000, 9000.pdf",
				imgUrl: "../img/instrumentalLiviano/Sysmex XN 9000.png",
			}
		],
	},
	{
		title: "Point of care",
		imgUrl: "../img/iconosNuevos/Point of care.png",
		hexColor: "#D8E6C0",
		productos: [
			{
				title: "Accutrend",
				brand: "Accutrend",
				category: "Lactato / Colesterol / Triglicéridos ",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/Accutrend.pdf",
				imgUrl: "../img/instrumentalLiviano/Accutrend.png",
			},
			{
				title: "cobas h 232",
				brand: "cobas",
				category: "Cardiología / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/cobas H232.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas h232.png",
			},
			{
				title: "Coagucheck XS",
				brand: "Coagucheck",
				category: "Coagulación / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/Coaguchek xs.pdf",
				imgUrl: "../img/instrumentalLiviano/Coaguchek XS.png",
			},
			{
				title: "Coagucheck Pro",
				brand: "Coagucheck",
				category: "Coagulación / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/Coaguchek pro.pdf",
				imgUrl: "../img/instrumentalLiviano/CoaguChek Pro.png",
			},
			{
				title: "LIAT",
				brand: "cobas",
				category: "Biología Molecular / Microbiología / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/Cobas Liat.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Liat.png",
			},
			{
				title: "Veritor",
				brand: "BD",
				category: "Lector de test rápidos / Microbiología / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/BD Veritor Plus.pdf",
				imgUrl: "../img/instrumentalLiviano/BD Veritor.png",
			},
			{
				title: "Opti CCA TS2",
				brand: "Opti",
				category: "Medio Interno / Point of Care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/OPTI CCA TS2.pdf",
				imgUrl: "../img/instrumentalLiviano/Opti CCA-TS2.png",
			},
		],
	},
	{
		title: "Anatomía Patológica",
		imgUrl: "../img/iconosNuevos/Anatomía Patológica.png",
		hexColor: "#E676BA",
		productos: [
			{
				title: "Benchmark GX",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Benchmark GX español.pdf",
				imgUrl: "../img/instrumentalLiviano/Benchmark GX.png",
			},
			{
				title: "Benchmark ultra",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Ventana ULTRA.pdf",
				imgUrl: "../img/instrumentalLiviano/Benchmark XT.png",
			},
			{
				title: "DP200 ",
				brand: "Ventana",
				category: "Anatomía Patológica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/DP 200.pdf",
				imgUrl: "../img/instrumentalLiviano/DP200.png",
			},
		],
	},
	{
		title: "Endocrinología, Inmuno, Marcadores tumorales",
		imgUrl: "../img/iconosNuevos/Endocrinología, Inmuno, Marcadores tumorales.png",
		hexColor: "#FFBF30",
		productos: [
			{
				title: "cobas e411",
				brand: "cobas",
				category: "Endocrinología / Inmunología / Marcadores Tumorales/ Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas e 411.png",
			},
			{
				title: "cobas c 503",
				brand: "cobas",
				category: "Endocrinología / Inmunología / Marcadores Tumorales/ Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 503.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 503.png",
			},
			{
				title: "cobas e 801",
				brand: "cobas",
				category: "Endocrinología / Inmunología / Marcadores Tumorales/ Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 801.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas e 801.png",
			},
		],
	},
	{
		title: "Química Clínica",
		imgUrl: "../img/iconosNuevos/Química Clínica.png",
		hexColor: "#6B8C49",
		productos: [
			{
				title: "cobas c 111",
				brand: "cobas",
				category: "Química Clínica / veterinaria ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas c111.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 111.png",
			},
			{
				title: "cobas c 311",
				brand: "cobas",
				category: "Química Clínica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas c 311.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 311.png",
			},
			{
				title: "cobas c 501",
				brand: "cobas",
				category: "Química Clínica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas c 501.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 501.png",
			},
			{
				title: "Metrolab 1600 DR",
				brand: "Metrolab",
				category: "Química Clínica / veterinaria",
				type: "Equipos Semiautomáticos",
				pdfUrl: "../docs/instrumentos/Metrolab 1600 DR.pdf",
				imgUrl: "../img/instrumentalLiviano/Metrolab 1600 DR.png",
			},
			{
				title: "CM 200",
				brand: "Wiener",
				category: "Química Clínica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/CM 200.pdf",
				imgUrl: "../img/instrumentalLiviano/CM 200.png",
			},
			{
				title: "CM 250",
				brand: "Wiener",
				category: "Química Clínica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/CM 250.pdf",
				imgUrl: "../img/instrumentalLiviano/CM 250.png",
			},
			{
				title: "BTS 350 Analizador Semiautomático",
				brand: "Biosystems",
				category: "Química Clínica / veterinaria",
				type: "Equipos Semiautomáticos",
				pdfUrl: "../docs/instrumentos/BTS 350.pdf",
				imgUrl: "../img/instrumentalLiviano/BTS 350.png",
			},
			{
				title: "Autoanalizador A 15",
				brand: "Biosystems",
				category: "Química Clínica / veterinaria",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/A15.pdf",
				imgUrl: "../img/instrumentalLiviano/Autoanalizador A 15.png",
			},
			{
				title: "Autoanalizador A 25",
				brand: "Biosystems",
				category: "Química Clínica",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/A25.pdf",
				imgUrl: "../img/instrumentalLiviano/Autoanalizador A 25.png",
			},
		],
	},
	{
		title: "Banco de sangre",
		imgUrl: "../img/iconosNuevos/Banco de sangre.png",
		hexColor: "#FF5757",
		productos: [
			{
				title: "cobas e 411",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas e 411.png",
			},
			{
				title: "cobas c 503",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 503.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 503.png",
			},
			{
				title: "cobas e 801",
				brand: "cobas",
				category:
					"Endocrinología / Inmunología / Marcadores Tumorales / Banco de Sangre",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas e 801.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas e 801.png",
			},
			{
				title: "cobas 5800",
				brand: "cobas",
				category: "Biología Molecular / NAT",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas 5800.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas 5800.png",
			},
		],
	},
	{
		title: "Electroforesis",
		imgUrl: "../img/iconosNuevos/Electroforesis.png",
		hexColor: "#FFE1BD",
		productos: [
			{
				title: "Minicap ",
				brand: "Sebia",
				category: "Electroforesis capilar",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Minicap.pdf",
				imgUrl: "../img/instrumentalLiviano/Minicap.png",
			},
			{
				title: "Capilarys 2 ",
				brand: "Sebia",
				category: "Electroforesis capilar",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Capillarys 2.pdf",
				imgUrl: "../img/instrumentalLiviano/Capilarys 2.png",
			},
			{
				title: "Capilarys 3 OCTA",
				brand: "Sebia",
				category: "Electroforesis capilar",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/BG_SEBIA_CAPILLARYS 3 OCTA.pdf",
				imgUrl: "../img/instrumentalLiviano/Capilarys 3 OCTA.png",
			},
		],
	},
	/*  Roche, BD, Wiener, --Dagon, Pobel, Lumen Glass, IVA, AHN, --Nipro,
	 --Hermax, --Guest, Doncella, --3M, Cris-Blan, NP, --Porta, Feather, Veda, Random, Tecnoclone,
	  Binding Site, Brizuela, Lab Lemos. */
	{
		title: "Software",
		imgUrl: "../img/iconosNuevos/Software.png",
		hexColor: "#D0D4D7",
		productos: [
			{
				title: "cobas Infinity",
				brand: "cobas",
				category: "Software",
				type: "Sistema de gestión de Laboratorio",
				pdfUrl: "../docs/instrumentos/cobas infinity.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Infinity.png",
			},
			{
				title: "Optimi",
				brand: "Optimi",
				category: "Software",
				type: "Sistema de gestión de Laboratorio",
				pdfUrl: "#",
				imgUrl: "../img/instrumentalLiviano/optimi.png",
			},
		],
	},
	{
		title: "Biología Molecular",
		imgUrl: "../img/iconosNuevos/Biología Molecular.png",
		hexColor: "#0697D5",
		productos: [
			{
				title: "cobas 5800",
				brand: "cobas",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas 5800.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas 5800.png",
			},
			{
				title: "cobas Liat",
				brand: "cobas",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas Liat.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Liat.png",
			},
			{
				title: "BD Max",
				brand: "BD",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Brochure_ BD MAX™ system 2023.pdf",
				imgUrl: "../img/instrumentalLiviano/BD Max.png",
			},
		],
	},
	{
		title: "Eritrosedimentación",
		imgUrl: "../img/iconosNuevos/Eritrosedimentaciòn.png",
		hexColor: "#0E0D0D",
		productos: [
			{
				title: "e32",
				brand: "Wiener",
				category: "",
				type: "",
				pdfUrl: "../docs/instrumentos/e32.pdf",
				imgUrl: "../img/instrumentalLiviano/e32.png",
			},
			{
				title: "Roller 20 LC",
				brand: "ALIFAX",
				category: "",
				type: "",
				pdfUrl: "../docs/instrumentos/Roller.pdf",
				imgUrl: "../img/instrumentalLiviano/Roller 20 LC.png",
			},
		],
	},
	{
		title: "Soluciones Integrales para Sueros",
		imgUrl: "../img/iconosNuevos/Soluciones para suero.png",
		hexColor: "#132E4A",

		productos: [
			{
				title: "cobas Pure",
				brand: "cobas",
				category: "Cardiología / Marcadores Tumorales / Serología/ Química",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas Pure.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Pure.png",
			},
			{
				title: "cobas Pro",
				brand: "cobas",
				category: "Cardiología / Marcadores Tumorales / Serología/ Química",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas Pro.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Pro.png",
			},
		],
	},
	{
		title: "Cardiología",
		imgUrl: "../img/iconosNuevos/Cardiología.png",
		hexColor: "#7B1314",
		productos: [
			{
				title: "cobas h232",
				brand: "cobas",
				category: "Cardiología / Point of care",
				type: "Equipos Point of Care",
				pdfUrl: "../docs/instrumentos/cobas H232.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas h232.png",
			},
			{
				title: "cobas e 411",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología",
				pdfUrl: "../docs/instrumentos/cobas e 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas e 411.png",
			},
			{
				title: "cobas Pure",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología/ Química",
				pdfUrl: "../docs/instrumentos/Cobas Pure.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Pure.png",
			},
			{
				title: "cobas Pro",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Cardiología / Marcadores Tumorales / Serología/ Química",
				pdfUrl: "../docs/instrumentos/Cobas Pro.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Pro.png",
			},
		],
	},
	{
		title: "Microbiología",
		imgUrl: "../img/iconosNuevos/Microbiología.png",
		hexColor: "#EE913E",
		productos: [
			{
				title: "FX 40",
				brand: "BD",
				category: "Hemocultivo / Microbiología",
				type: "Equipos Automáticos ",
				pdfUrl: "../docs/instrumentos/FX 40.pdf",
				imgUrl: "../img/instrumentalLiviano/FX 40.png",
			},
			{
				title: "FX TOP",
				brand: "BD",
				category: "Hemocultivo / Microbiología",
				type: "Equipos Automáticos ",
				pdfUrl: "#",
				imgUrl: "../img/instrumentalLiviano/FX TOP.png",
			},
			{
				title: "M50",
				brand: "BD",
				category:
					"Identificación Microbiana / Sensibilidad a antibióticos / Microbiología",
				type: "Equipos Automáticos ",
				pdfUrl: "../docs/instrumentos/M50.pdf",
				imgUrl: "../img/instrumentalLiviano/M50.png",
			},
			{
				title: "MALDI TOF ",
				brand: "BD Bruker ",
				category:
					"Identificación Microbiana / Sensibilidad a antibióticos / Microbiología",
				type: "Equipos Automáticos ",
				pdfUrl: "",
				imgUrl: "../img/instrumentalLiviano/MALDI TOF.png",
			},
			{
				title: "BD Max",
				brand: "BD",
				category: "Biología Molecular",
				type: "Equipos Automáticos ",
				pdfUrl: "../docs/instrumentos/Brochure_ BD MAX™ system 2023.pdf",
				imgUrl: "../img/instrumentalLiviano/BD Max.png",
			},
			{
				title: "BD Veritor",
				brand: "BD",
				category: "Lector de test rápido / Point of care / Microbiología",
				type: "Equipos Semiautomático",
				pdfUrl: "../docs/instrumentos/BD Veritor Plus.pdf",
				imgUrl: "../img/instrumentalLiviano/BD Veritor.png",
			},
			{
				title: "cobas Liat",
				brand: "cobas ",
				category: "Biología Molecular / Point of care",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas Liat.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas Liat.png",
			},
			{
				title: "cobas 5800",
				brand: "cobas ",
				category: "Biología Molecular / NAT ",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas 5800.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas 5800.png",
			},
		],
	},
	{
		title: "Veterinaria",
		imgUrl: "../img/iconosNuevos/Veterinaria.png",
		hexColor: "#5271FF",
		productos: [
			{
				title: "Diestro VET 103 ",
				brand: "Diestro",
				category: "Veterinaria",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/DIESTRO 103.pdf",
				imgUrl: "../img/instrumentalLiviano/Diestro VET 103.png",
			},
			{
				title: "Metrolab 1600 DR",
				brand: "Metrolab",
				category: "Química Clínica / veterinaria",
				type: "Equipos Semiautomáticos",
				pdfUrl: "../docs/instrumentos/Metrolab 1600 DR.pdf",
				imgUrl: "../img/instrumentalLiviano/Metrolab 1600 DR.png",
			},
			{
				title: "BTS 350 Analizador Semiautomático",
				brand: "Biosystems",
				category: "Química Clínica / veterinaria",
				type: "Equipos Semiautomáticos",
				pdfUrl: "../docs/instrumentos/BTS 350.pdf",
				imgUrl: "../img/instrumentalLiviano/BTS 350.png",
			},
			{
				title: "cobas c 111",
				brand: "cobas",
				category: "Química Clínica / veterinaria",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas c111.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas c 111.png",
			},
			{
				title: "Autoanalizador A 15",
				brand: "Biosystems",
				category: "Química Clínica / veterinaria",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/A15.pdf",
				imgUrl: "../img/instrumentalLiviano/Autoanalizador A 15.png",
			},
			{
				title: "cobas u 411",
				brand: "cobas",
				category: "Orina / Veterinaria",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas u 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 411.png",
			},
		],
	},
	{
		title: "Citrometría de flujo",
		imgUrl: "../img/iconosNuevos/Citometría de flujo.png",
		hexColor: "#F2BC7D",
		productos: [
			{
				title: "BD FACSAria",
				brand: "BD",
				category: "Citometría de Flujo",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/BD_FACSAria.pdf",
				imgUrl: "../img/instrumentalLiviano/BD FACSAria.png",
			},
			{
				title: "BD FACSCanto",
				brand: "BD",
				category: "Citometría de Flujo",
				type: "Equipos Automáticos",
				pdfUrl:
					"../docs/instrumentos/X23-8742-03_BD_FACSCanto_II_EU.pdf",
				imgUrl: "../img/instrumentalLiviano/BD FACSCanto.png",
			},
		],
	},
	{
		title: "Medio interno",
		imgUrl: "../img/iconosNuevos/Medio Interno.png",
		hexColor: "#FFD5F2",
		productos: [
			{
				title: "cobas b221",
				brand: "cobas",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas b221.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas b221.png",
			},
			{
				title: "Analizador de gases en sangre Portatil",
				brand: "Opti Medical",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/OPTI CCA TS2.pdf",
				imgUrl: "../img/instrumentalLiviano/Opti CCA-TS2.png",
			},
			{
				title: "AVL 9180",
				brand: "AVL",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/AVL 9180.pdf",
				imgUrl: "../img/instrumentalLiviano/AVL 9180.png",
			},
			{
				title: "Analizador semiautomático de electrolitos",
				brand: "Diestro",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/DIESTRO 103.pdf",
				imgUrl: "../img/instrumentalLiviano/Diestro VET 103.png",
			},
			{
				title: "Analizador automático de electrolitos ",
				brand: "Diestro",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/DIESTRO 103.pdf",
				imgUrl: "../img/instrumentalLiviano/Diestro VET 103.png",
			},
			{
				title: "EXIAS e1",
				brand: "EXIAS Medical",
				category: "Medio interno",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/EXIAS_E1Analyzer.pdf",
				imgUrl: "../img/instrumentalLiviano/EXIAS e1.png",
			},
		],
	},
	{
		title: "Coagulación",
		imgUrl: "../img/iconosNuevos/Coagulaciòn.png",
		hexColor: "#A7EAED",
		productos: [
			{
				title: "Coaguchek XS",
				brand: "Coagucheck",
				category: "Equipos Point of Care",
				type: "Coagulación / Point of Care",
				pdfUrl: "../docs/instrumentos/Coaguchek xs.pdf",
				imgUrl: "../img/instrumentalLiviano/Coaguchek XS.png",
			},
			{
				title: "CoaguChek Pro",
				brand: "Coagucheck",
				category: "Equipos Point of Care",
				type: "Coagulación / Point of Care",
				pdfUrl: "../docs/instrumentos/Coaguchek pro.pdf",
				imgUrl: "../img/instrumentalLiviano/CoaguChek Pro.png",
			},
			{
				title: "t411",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/cobas t 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas t411.png",
			},
			{
				title: "t511",
				brand: "cobas",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/cobas t 511.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas t511.png",
			},
			{
				title: "STA Compact Max3",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/STA Satellite Max.pdf",
				imgUrl: "../img/instrumentalLiviano/STA Compact Max3.png",
			},
			{
				title: "Star Max",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/STA Satellite Max.pdf",
				imgUrl: "../img/instrumentalLiviano/Start Max.png",
			},
			{
				title: "STA Satellite Max",
				brand: "Stago",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/STA Satellite Max.pdf",
				imgUrl: "../img/instrumentalLiviano/STA Satellite Max.png",
			},
			{
				title: "DT100",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/DT 100.pdf",
				imgUrl: "../img/instrumentalLiviano/DT100.png",
			},
			{
				title: "KC4",
				brand: "Tcoag",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/KC4.pdf",
				imgUrl: "../img/instrumentalLiviano/KC4.png",
			},
			{
				title: "Destiny Plus",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/DESTINY PLUS.pdf",
				imgUrl: "../img/instrumentalLiviano/Destiny Plus.png",
			},
			{
				title: "Destiny Max",
				brand: "Tcoag",
				category: "Equipos Automáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/DESTINY MAX.pdf",
				imgUrl: "../img/instrumentalLiviano/Destiny Max.png",
			},
			{
				title: "Col1",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/COL 1 , 2 y 4.pdf",
				imgUrl: "../img/instrumentalLiviano/Col1.png",
			},
			{
				title: "Col2",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/COL 1 , 2 y 4.pdf",
				imgUrl: "../img/instrumentalLiviano/Col2.png",
			},
			{
				title: "Col4",
				brand: "Wiener",
				category: "Equipos Semiutomáticos",
				type: "Coagulación",
				pdfUrl: "../docs/instrumentos/COL 1 , 2 y 4.pdf",
				imgUrl: "../img/instrumentalLiviano/Col4.png",
			},
		],
	},
	{
		title: "Orina",
		imgUrl: "../img/iconosNuevos/Orina.png",
		hexColor: "#7F7B7E",
		productos: [
			{
				title: "cobas u 411",
				brand: "cobas",
				category: "Orina",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas u 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 411.png",
			},
			{
				title: "Módulo de estación de sedimento",
				brand: "cobas",
				category: "Orina",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas u 411.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 411.png",
			},
			{
				title: "cobas u 601",
				brand: "cobas",
				category: "Orina",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas u 601.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 601.png",
			},
			{
				title: "cobas u 701",
				brand: "cobas",
				category: "Orina",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/Cobas u 701.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 701.png",
			},
			{
				title: "cobas u 6500",
				brand: "cobas",
				category: "Orina",
				type: "Equipos Automáticos",
				pdfUrl: "../docs/instrumentos/cobas 6500.pdf",
				imgUrl: "../img/instrumentalLiviano/cobas u 6500.png",
			},
		],
	},
];
