export const descartables = [
	{
		title: "Preanalítica",
		items: ["Sistema Vacutainer", "Microtainer"],
		logos: [
			"../img/representadas/bd.png", 
			"../img/representadas/tecnon.png",
			"../img/representadas/feather.png",
			"../img/representadas/hda.png",
			"../img/representadas/deltalab.png",
			"../img/representadas/terumo.png",
			"../img/representadas/ahn.png",
			"../img/representadas/hermax.png",
			"../img/representadas/pobel.png",
			"../img/representadas/lumenglass.png",
			"../img/representadas/iva.png",
			"../img/representadas/biocap.png",
			"../img/representadas/doncella.png",
			"../img/representadas/crisblan.png",
		],
	},
	{
		title: "Material de Plastico",
		items: [
			"Agujas",
			"Bolsas",
			"Cassettes",
			"Crioviales",
			"Eppendorf",
			"Gradillas",
			"Hisopos",
			"Jeringas",
			"Pipetas",
			"Placas de Petri",
			"Recolectores para Heces",
			"Recolectores para Orina",
			"Tips",
			"Tubos preparados",
			"Tubos secos",
			"Otros",
		],
		logos: [
			"../img/representadas/bd.png", 
			"../img/representadas/tecnon.png",
			"../img/representadas/feather.png",
			"../img/representadas/hda.png",
			"../img/representadas/deltalab.png",
			"../img/representadas/terumo.png",
			"../img/representadas/ahn.png",
			"../img/representadas/hermax.png",
			"../img/representadas/pobel.png",
			"../img/representadas/lumenglass.png",
			"../img/representadas/iva.png",
			"../img/representadas/biocap.png",
			"../img/representadas/doncella.png",
			"../img/representadas/crisblan.png",
		],
	},
	{
		title: "Material de Vidrio",
		items: [
			"Botellas",
			"Buretas",
			"Camara de Neubauer",
			"Capilares",
			"Cubrecamaras",
			"Cubreobjetos",
			"Embudos",
			"Erlenmeyer",
			"Frascos",
			"Jeringas",
			"Kitasatos",
			"Matraces",
			"Pipetas",
			"Placas de Petri",
			"Portaobjetos",
			"Probetas",
			"Tubos",
			"Vasos de Precipitados",
			"Otros",
		],
		logos: [
			"../img/representadas/bd.png", 
			"../img/representadas/tecnon.png",
			"../img/representadas/feather.png",
			"../img/representadas/hda.png",
			"../img/representadas/deltalab.png",
			"../img/representadas/terumo.png",
			"../img/representadas/ahn.png",
			"../img/representadas/hermax.png",
			"../img/representadas/pobel.png",
			"../img/representadas/lumenglass.png",
			"../img/representadas/iva.png",
			"../img/representadas/biocap.png",
			"../img/representadas/doncella.png",
			"../img/representadas/crisblan.png",
		],
	},
	{
		title: "Material en General",
		items: [
			"Alcohol",
			"Algodón",
			"Ansas",
			"Apósitos",
			"Cepillos",
			"Cestos",
			"Cintas",
			"Etiquetas",
			"Gradillas",
			"Guantes",
			"Precintos",
			"Tapones",
			"Termómetros",
			"Timer",
			"Otros",
		],
		logos: [
			"../img/representadas/bd.png", 
			"../img/representadas/tecnon.png",
			"../img/representadas/feather.png",
			"../img/representadas/hda.png",
			"../img/representadas/deltalab.png",
			"../img/representadas/terumo.png",
			"../img/representadas/ahn.png",
			"../img/representadas/hermax.png",
			"../img/representadas/pobel.png",
			"../img/representadas/lumenglass.png",
			"../img/representadas/iva.png",
			"../img/representadas/biocap.png",
			"../img/representadas/doncella.png",
			"../img/representadas/crisblan.png",
		],
	},
];
