export const descartables = [
  {
    title: "Material de Plastico",
    items: [
      "Agujas",
      "Bolsas",
      "Cassettes",
      "Crioviales",
      "Eppendorf",
      "Gradillas",
      "Hisopos",
      "Jeringas",
      "Pipetas",
      "Placas de Petri",
      "Recolectores para Heces",
      "Recolectores para Orina",
      "Tips",
      "Tubos preparados",
      "Tubos secos",
      "Otros",
    ],
    logos: [
      "../img/representadas/tecnon.png",
      "../img/representadas/deltalab.png",
      "../img/representadas/terumo.png",
      "../img/representadas/ahn.png",
      "../img/representadas/nipro.png",
      "../img/representadas/bd.png",
      "../img/representadas/massobact.png",
      "../img/representadas/hermax.png",
      "../img/representadas/dagon.png",
      "../img/representadas/guest.png",
    ],
  },
  {
    title: "Material de Vidrio",
    items: [
      "Botellas",
      "Buretas",
      "Camara de Neubauer",
      "Capilares",
      "Cubrecamaras",
      "Cubreobjetos",
      "Embudos",
      "Erlenmeyer",
      "Frascos",
      "Jeringas",
      "Kitasatos",
      "Matraces",
      "Pipetas",
      "Placas de Petri",
      "Portaobjetos",
      "Probetas",
      "Tubos",
      "Vasos de Precipitados",
      "Otros",
    ],
    logos: [
      "../img/representadas/deltalab.png",
      "../img/representadas/dagon.png",
      "../img/representadas/obel.jpg",
      "../img/representadas/lumenglass.png",
      "../img/representadas/iva.png",
      "../img/representadas/biocap.png",
    ],
  },
  {
    title: "Material en General",
    items: [
      "Alcohol",
      "Algodón",
      "Ansas",
      "Apósitos",
      "Cepillos",
      "Cestos",
      "Cintas",
      "Etiquetas",
      "Gradillas",
      "Guantes",
      "Precintos",
      "Tapones",
      "Termómetros",
      "Timer",
      "Otros",
    ],
    logos: [
      "../img/representadas/deltalab.png",
      "../img/representadas/nipro.png",
      "../img/representadas/bd.png",
      "../img/representadas/dagon.jpg",
      "../img/representadas/obel.jpg",
      "../img/representadas/3m.png",
      "../img/representadas/doncella.png",
      "../img/representadas/crisblab.png",
      "../img/representadas/np.png",
      "../img/representadas/guest.png",
      "../img/representadas/porta.png",
      "../img/representadas/feather.jpg",
    ],
  },
];
