const categoriasInstrumentalLiviano = [
	{
		categoria: "Agitadores",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Balanzas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Baños termostáticos",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Cabina de Flujo Laminar",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Centrífugas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Desiladores",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Dispensadores",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Estufas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Lavadores",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Lectores de Placas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Micropipetas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Microscopios",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Desecador de Vidrio",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Desecador de Plástico",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Gradilla para Aspiradores de Pipetas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Aspiradores de Pipetas",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
	{
		categoria: "Dispensador de PortaObjetos",
		logos: [
			"../img/representadas/deltalab.png",
			"../img/representadas/gelec.png",
			"../img/representadas/sanjor.png",
			"../img/representadas/vicking.png",
			"../img/representadas/mikoba.png",
			"../img/representadas/ohaus.png",
			"../img/representadas/dalvo.png",
			"../img/representadas/mindray.png",
		],
	},
];
