export const tiposDeInstrumentales = [
  "Todos",
  "Agitadores",
  "Balanzas",
  "Baños Termostáticos",
  "Cabina de Flujo Laminar",
  "Centrífugas",
  "Destiladores",
  "Dispensadores",
  "Estufas",
  "Esterilización",
  "Lavadoras Ultrasónicas",
  "Lavadores",
  "Lector de Placas",
  "Micropipetas",
  "Microscopios",
  "Otros",
];

export const productos = [
  {
    id: "1",
    title: "Desecador en Vidrio",
    imgUrl: "../img/productos/desecadorDeVidrio.jpeg",
    manufacturerLogoUrl: "../img/representadas/deltalab.png",
    marca: "DeltaLab",
    modelo: "19232/19235",
    tipo: "Instrumental Liviano",
    categoria: "Otros",
    garantia: "Por defectos de fabricación",
    caracteristicas:
      "Cuerpo y tapa fabricados en vidrio borosilicato 3.3. Alto grado de resistencia química. Pueden utilizarse desecantes como cloruro cálcico, gel de sílice, pentóxido de fósforo e incluso ácido sulfúrico. Para su utilización el usuario debe limpiar las superficies de sellado y lubricarlas con grasa para vacío. Puede mantener un vacío a 500 mm Hg durante 24 horas.",
    dimensiones: "Ø 200 mm, altura 270 mm.",
  },
  {
    id: "2",
    title: "Flujo Laminar FVL 1300",
    imgUrl: "../img/productos/CabinaDeFlujoLaminar-FVL1300.png",
    manufacturerLogoUrl: "",
    marca: "Sabella",
    modelo: "FVL 1300",
    tipo: "Instrumental Liviano",
    categoria: "Cabina de Flujo Laminar",
    garantia: "",
    caracteristicas:
      "Cuerpo y tapa fabricados en vidrio borosilicato 3.3. Alto grado de resistencia química. Pueden utilizarse desecantes como cloruro cálcico, gel de sílice, pentóxido de fósforo e incluso ácido sulfúrico. Para su utilización el usuario debe limpiar las superficies de sellado y lubricarlas con grasa para vacío. Puede mantener un vacío a 500 mm Hg durante 24 horas.",
    dimensiones: "Ø 200 mm, altura 270 mm.",
  },
  {
    id: "3",
    title: "Estufa de Esterilización",
    imgUrl: "../img/productos/estufaDeEstarilizacionDalvo.jpg",
    manufacturerLogoUrl: "",
    marca: "Dalvo",
    modelo: "Premium",
    tipo: "Instrumental Liviano",
    categoria: "Esterilización",
    garantia: "Un año",
    caracteristicas:
      "Cuerpo y tapa fabricados en vidrio borosilicato 3.3. Alto grado de resistencia química. Pueden utilizarse desecantes como cloruro cálcico, gel de sílice, pentóxido de fósforo e incluso ácido sulfúrico. Para su utilización el usuario debe limpiar las superficies de sellado y lubricarlas con grasa para vacío. Puede mantener un vacío a 500 mm Hg durante 24 horas.",
    dimensiones: "Ø 200 mm, altura 270 mm.",
  },
];
