export const tiposDeInstrumentales = [
  "Agitadores",
  "Balanzas",
  "Baños Termostáticos",
  "Cabina de Flujo Laminar",
  "Centrífugas",
  "Destiladores",
  "Dispensadores",
  "Estufas",
  "Lavadoras Ultrasónicas",
  "Lavadores",
  "Lector de Placas",
  "Micropipetas",
  "Microscopios",
  "Otros",
];

export const productos = [
  {
    id: "1",
    title: "Desecador en Vidrio",
    imgUrl: "../img/desecadorDeVidrio.jpeg",
    marca: "DeltaLab",
    modelo: "19232/19235",
    tipo: "Instrumental Liviano",
    categoria: "Otros",
    garantia: "Por defectos de fabricación",
  },
  {
    id: "2",
    title: "Desecador en Vidrio",
    imgUrl: "../img/desecadorDeVidrio.jpeg",
    marca: "DeltaLab",
    modelo: "19232/19235",
    tipo: "Instrumental Liviano",
    categoria: "Otros",
    garantia: "Por defectos de fabricación",
  },
  {
    id: "3",
    title: "Desecador en Vidrio",
    imgUrl: "../img/desecadorDeVidrio.jpeg",
    marca: "DeltaLab",
    modelo: "19232/19235",
    tipo: "Instrumental Liviano",
    categoria: "Otros",
    garantia: "Por defectos de fabricación",
  },
];
