name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.1.2
        with:
          hostname: 'https://neo.servidoraweb.net'
          repository_root: '/home4/medmedi/repositories/mm'
          branch: master
          cpanel_token: '4IZYYOUYX8M3PRBCHCXY89Q0PFGEKTNF'
          cpanel_username: medmedi
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
          
